<a href="https://colab.research.google.com/github/hackinglove/ECG_capacity/blob/main/ECG001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 相关库导入



> 本模型采用神经网络算法，采用python3语言和Tensorflow框架，从文件中读取待处理数据进行训练，故需导入numpy，tenserflow，matplotlib等库。


  代码如下：



In [47]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.4.1


# 2. 数据预处理

# 2.1 导入数据
  从文件中导入分析原始数据所需各个特征的数据，包括心率，心率变异性的指标等等。代码如下：

In [82]:
cols = range(0,65)
cols = tuple(cols)
train_data = np.loadtxt(open("HRVdata1per0.5min.csv","rb"), delimiter = ",", skiprows = 0, usecols = cols, max_rows=500)
train_label = np.loadtxt(open("HRVdata1per0.5min.csv","rb"),dtype=int, delimiter = ",", skiprows = 0, usecols = (67), max_rows=500)
train_label = train_label - 1

# 2.2 浏览数据

In [75]:
train_data[1]

array([0.35947712, 0.2055709 , 0.21672185, 0.24643824, 0.17117117,
       0.3661484 , 0.49289617, 0.56335616, 0.32483248, 0.24330717,
       0.18741201, 0.15839162, 0.22636735, 0.24660221, 0.25068783,
       0.21740027, 0.27433155, 0.25467035, 0.23892929, 0.59157423,
       0.76030928, 0.15378255, 0.1277533 , 0.11863758, 0.11541325,
       0.10787522, 0.31152997, 0.30092406, 0.22331975, 0.29108363,
       0.24926058, 0.29131618, 0.5374675 , 0.62945662, 0.42225333,
       0.22414981, 0.15913959, 0.15713361, 0.17294587, 0.2321269 ,
       0.29872641, 0.28761129, 0.22281992, 0.23098267, 0.50557306,
       0.19605915, 0.18880507, 0.69619539, 0.71262001, 0.51298485,
       0.35856786, 0.36925207, 0.26350461, 0.51923077, 0.43478261,
       0.50480769, 0.41538462, 0.48431372, 0.        , 0.        ,
       0.52380952, 1.        , 0.64285714, 0.7635468 , 0.63736264])

In [50]:
len(train_label)

500

In [83]:
train_label

array([1, 2, 2, 3, 4, 2, 2, 2, 3, 0, 1, 3, 3, 3, 4, 3, 3, 0, 3, 3, 1, 3,
       2, 2, 0, 3, 2, 0, 2, 3, 3, 4, 2, 3, 2, 0, 2, 2, 4, 2, 2, 2, 2, 2,
       3, 2, 0, 2, 0, 3, 2, 3, 1, 3, 2, 1, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2,
       2, 2, 3, 2, 1, 2, 2, 1, 1, 2, 2, 4, 1, 4, 2, 4, 3, 3, 4, 2, 3, 3,
       0, 2, 3, 3, 3, 2, 2, 1, 2, 3, 4, 2, 4, 1, 0, 2, 3, 3, 2, 3, 3, 2,
       1, 2, 2, 2, 3, 4, 2, 1, 2, 2, 2, 2, 4, 3, 4, 3, 4, 2, 3, 2, 0, 2,
       2, 2, 4, 2, 3, 2, 4, 2, 4, 2, 2, 2, 2, 1, 2, 4, 0, 4, 2, 3, 2, 2,
       3, 4, 3, 4, 3, 2, 4, 2, 1, 2, 2, 0, 3, 3, 1, 2, 3, 2, 3, 0, 4, 3,
       2, 1, 2, 2, 2, 2, 2, 3, 2, 2, 1, 4, 2, 2, 3, 4, 2, 2, 2, 3, 2, 4,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 4, 3, 3, 2, 4, 4, 4, 2, 4, 3, 0,
       4, 0, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 4, 2, 2, 1, 2, 1, 2, 3, 0, 2,
       2, 3, 2, 2, 1, 3, 4, 4, 2, 2, 1, 3, 2, 3, 2, 2, 2, 3, 2, 3, 3, 2,
       2, 2, 2, 0, 1, 2, 1, 4, 4, 2, 2, 4, 3, 2, 3, 2, 2, 0, 2, 1, 2, 2,
       3, 2, 2, 4, 2, 2, 2, 2, 2, 1, 2, 3, 1, 3, 4,

# 3. 模型搭建

In [123]:
model = keras.Sequential([
    keras.layers.Dense(48, activation='relu'),
    keras.layers.Dense(48, activation='relu'),
    keras.layers.Dense(5)
])

In [124]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# 4. 模型训练

In [126]:
model.fit(train_data,train_label,epochs=200)

Epoch 1/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0733 - accuracy: 0.9840
Epoch 2/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0729 - accuracy: 0.9820
Epoch 3/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0635 - accuracy: 0.9880
Epoch 4/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0614 - accuracy: 0.9840
Epoch 5/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0625 - accuracy: 0.9900
Epoch 6/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0689 - accuracy: 0.9860
Epoch 7/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0677 - accuracy: 0.9880
Epoch 8/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0629 - accuracy: 0.9900
Epoch 9/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0620 - accuracy: 0.9860
Epoch 10/200
16/16 [==============================] - 0s 2ms/step - loss: 0.0617 - accuracy: 0.9820
Epoch 11/

# 5. 模型检验

In [101]:
test_data = np.loadtxt(open("HRVdata1per0.5mintest.csv","rb"), delimiter = ",", skiprows = 0, usecols = cols, max_rows=549)
test_label = np.loadtxt(open("HRVdata1per0.5mintest.csv","rb"),dtype=int, delimiter = ",", skiprows = 0, usecols = (67), max_rows=549)
test_label = test_label - 1

In [127]:
test_loss, test_acc = model.evaluate(test_data,  test_label, verbose=2)


18/18 - 0s - loss: 1.1274 - accuracy: 0.8124


In [128]:
probability_model = tf.keras.Sequential([model, 
                        tf.keras.layers.Softmax()])

In [129]:
predictions = probability_model.predict(test_data)

In [130]:
predictions[3]

array([1.6260089e-17, 2.3017149e-07, 9.9999976e-01, 1.6574025e-13,
       2.0236450e-19], dtype=float32)

In [131]:
np.argmax(predictions[3])

2