<a href="https://colab.research.google.com/github/hackinglove/ECG_capacity/blob/main/ECG001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 相关库导入



> 本模型采用神经网络算法，采用python3语言和Tensorflow框架，从文件中读取待处理数据进行训练，故需导入numpy，tenserflow，matplotlib等库。


  代码如下：



In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.4.1


# 2. 数据预处理

# 2.1 导入数据
  从文件中导入分析原始数据所需各个特征的数据，包括心率，心率变异性的指标等等。代码如下：

In [39]:
cols = range(0,10)
cols = tuple(cols)
train_data = np.loadtxt(open("1.csv","rb"), delimiter = ",", skiprows = 0, usecols = cols)
train_label = np.loadtxt(open("1.csv","rb"), delimiter = ",", skiprows = 0, usecols = (10))

# 2.2 浏览数据

In [40]:
print(train_data)
print(train_label)

[[1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9. 1.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9. 2.]]
[1. 1. 1.]


# 3. 模型搭建

# 4. 模型训练

# 5. 模型检验